# Change these first
owner: nubispc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Nubis Website
    url: https://nubis-pc.eu
  - name: S3
    url: https://s3.nbfc.io
  - name: owncloud
    url: https://owncloud.nbfc.io
  - name: Main server
    url: https://mail.nubificus.co.uk
  - name: Monitoring-1
    url: https://monit.nubificus.co.uk
  - name: Monitoring-2
    url: https://grafana.nephos.gr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.nephos.gr
  # baseUrl: /your-repo-name
  logoUrl: https://nubis-pc.eu/images/nubis-logo-scaled-negative.png
  name: NUBIS uptime
  introTitle: "Nubis status page"
  introMessage: This is a status page for services hosted by Nubis and Nubificus.
  navbar:
    - title: Status
      href: /
    - title: Nubis
      href: https://nubis-pc.eu
    - title: Nubificus
      href: https://nubificus.co.uk
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
